### ISSUE TITLE
Source code for phone application

### ISSUE THREAD

**Issue by clach04** [jonathanrjpereira/8051-Bluetooth-Door-Lock#1]
The docx file and description mention a smartphone app. I can't find it in the repo.

**Comment by jonathanrjpereira** [comment]
In this project, I used a Bluetooth controller app from the PlayStore (since I don't how to write Android Apps). Hence I don't have the source code for the phone application.

Although any Bluetooth app capable of sending single characters (Buttons) to a device & displaying messages(Lock Status, Error Messages) on a phone screen should work fine. The hardware circuit simply communicates with the HC-05 via the serial port.

I used one of these apps. Either one will work with the circuit:
[Arduino Bluetooth Controller](https://play.google.com/store/apps/details?id=com.giumig.apps.bluetoothserialmonitor
)
[Bluetooth Terminal](https://play.google.com/store/apps/details?id=project.bluetoothterminal
)  

If I had more time to complete this project, I would have probably made an app using either [Blynk](https://www.blynk.cc/) or [MIT App Inventor](http://ai2.appinventor.mit.edu/)
That being said, I'm open to working with Android/iOS devs in order to make a custom app for this project.
